export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESSS = 'ADD_PRODUCT_SUCCESSS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL'

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL'

export const UPDATE_PRODUCT_BY_ID = 'UPDATE_PRODUCT_BY_ID'
export const UPDATE_PRODUCT_BY_ID_SUCCESS = 'UPDATE_PRODUCT_BY_ID_SUCCESS'
export const UPDATE_PRODUCT_BY_ID_FAIL = 'UPDATE_PRODUCT_BY_ID_FAIL'

export const REMOVE_PRODUCT_BY_ID = 'REMOVE_PRODUCT_BY_ID'
export const REMOVE_PRODUCT_BY_ID_SUCCESS = 'REMOVE_PRODUCT_BY_ID_SUCCESS'
export const REMOVE_PRODUCT_BY_ID_FAIL = 'REMOVE_PRODUCT_BY_ID_FAIL'

export const RESET_PRODUCT = 'RESET_PRODUCT'

// =====================CUSTOM ACTIONS================================

export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL'

export const GET_VARIATION = 'GET_VARIATION'
export const GET_VARIATION_SUCCESS = 'GET_VARIATION_SUCCESS'
export const GET_VARIATION_FAIL = 'GET_VARIATION_FAIL'

export const IS_SUCCESS_DONE = 'IS_SUCCESS_DONE';