export const ADD_DATA = 'ADD_DATA'
export const ADD_DATA_SUCCESSS = 'ADD_DATA_SUCCESSS'
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL'

export const GET_ALL_DATA = 'GET_ALL_DATA'
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS'
export const GET_ALL_DATA_FAIL = 'GET_ALL_DATA_FAIL'

export const GET_DATA_BY_ID = 'GET_DATA_BY_ID'
export const GET_DATA_BY_ID_SUCCESS = 'GET_DATA_BY_ID_SUCCESS'
export const GET_DATA_BY_ID_FAIL = 'GET_DATA_BY_ID_FAIL'

export const UPDATE_DATA_BY_ID = 'UPDATE_DATA_BY_ID'
export const UPDATE_DATA_BY_ID_SUCCESS = 'UPDATE_DATA_BY_ID_SUCCESS'
export const UPDATE_DATA_BY_ID_FAIL = 'UPDATE_DATA_BY_ID_FAIL'

export const REMOVE_DATA_BY_ID = 'REMOVE_DATA_BY_ID'
export const REMOVE_DATA_BY_ID_SUCCESS = 'REMOVE_DATA_BY_ID_SUCCESS'
export const REMOVE_DATA_BY_ID_FAIL = 'REMOVE_DATA_BY_ID_FAIL'

export const RESET_DATA = 'RESET_DATA'

export const REDIRECTION = 'REDIRECTION'